theme: jekyll-theme-hacker
title: welcome to koval77's projects website!
description: Here you can admire some of my first steps into programming. Bookmark it to see any updates I will make in the future.
